# Generated by Django 5.2.14 on 2026-05-22 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtagjesus', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hjblogpostpage',
            name='youtube_url',
            field=models.URLField(blank=True, default='', help_text='YouTube Short / video URL. When filled, replaces the hero image on the page (image is still used for the share preview). Accepts youtu.be/<id>, youtube.com/shorts/<id>, youtube.com/watch?v=<id>, or just the <id>.'),
        ),
        migrations.AlterField(
            model_name='hjblogpostpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Hero image. Also used as the OG / preview image when sharing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
