# Generated by Django 5.2.14 on 2026-05-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtagjesus', '0003_add_chapter_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hjblogpostpage',
            name='body_md',
            field=models.TextField(blank=True, help_text='Post storytelling (shown in blog listing).'),
        ),
        migrations.AlterField(
            model_name='hjblogpostpage',
            name='intro',
            field=models.CharField(blank=True, help_text='OG/meta description.', max_length=400),
        ),
    ]
