# Generated by Django 5.2.14 on 2026-05-09 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpage',
            name='coming_soon',
            field=models.BooleanField(default=True, help_text="If true, page shows 'coming soon' and the buy button is hidden."),
        ),
        migrations.CreateModel(
            name='BookPostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Post date')),
                ('ref', models.CharField(blank=True, help_text="Bible reference, e.g. 'João 13:1-17'.", max_length=200)),
                ('body_md', models.TextField(blank=True, help_text='Markdown source.')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
