# Generated by Django 5.2.14 on 2026-05-09 02:31

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_bookpage_coming_soon_bookpostpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcatalogpage',
            name='intro_pt',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookpage',
            name='description_pt',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookpage',
            name='subtitle_pt',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
