# Generated by Django 5.2.14 on 2026-05-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_bookcatalogpage_intro_pt_bookpage_description_pt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcatalogpage',
            name='title_pt',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
