# Generated by Django 5.2.14 on 2026-05-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_bookcatalogpage_title_pt'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpostpage',
            name='summary',
            field=models.CharField(blank=True, help_text='1-2 sentence excerpt shown on listings (auto-generated by extract_book_post_meta).', max_length=400),
        ),
        migrations.AddField(
            model_name='bookpostpage',
            name='summary_pt',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='bookpostpage',
            name='title_pt',
            field=models.CharField(blank=True, help_text='PT version of the page title.', max_length=255),
        ),
    ]
