# Generated by Django 5.2.14 on 2026-06-20 00:30

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioBookingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('heading', models.CharField(blank=True, default='Book a conversation', max_length=160)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('hours_note', models.CharField(blank=True, help_text="e.g. 'Weekdays, 11:00–19:00.'", max_length=200)),
                ('heading_pt', models.CharField(blank=True, max_length=160)),
                ('intro_pt', wagtail.fields.RichTextField(blank=True)),
                ('hours_note_pt', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StudioHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_eyebrow', models.CharField(blank=True, help_text='Small eyebrow above the hero headline.', max_length=160)),
                ('hero_headline', wagtail.fields.RichTextField(blank=True, help_text='Hero headline (use <em> for emphasis).')),
                ('hero_subhead', wagtail.fields.RichTextField(blank=True, help_text='Short paragraph under the hero headline.')),
                ('cta_label', models.CharField(blank=True, default='Book a conversation', max_length=80)),
                ('services_heading', models.CharField(blank=True, max_length=160)),
                ('services_intro', wagtail.fields.RichTextField(blank=True)),
                ('process_heading', models.CharField(blank=True, max_length=160)),
                ('process_intro', wagtail.fields.RichTextField(blank=True)),
                ('cases_heading', models.CharField(blank=True, max_length=160)),
                ('cases_intro', wagtail.fields.RichTextField(blank=True)),
                ('about_heading', models.CharField(blank=True, max_length=160)),
                ('about_body', wagtail.fields.RichTextField(blank=True)),
                ('closing_heading', models.CharField(blank=True, max_length=200)),
                ('closing_body', wagtail.fields.RichTextField(blank=True)),
                ('stack_note', wagtail.fields.RichTextField(blank=True, help_text="Small 'stack' line in the footer (cloud/tools).")),
                ('hero_eyebrow_pt', models.CharField(blank=True, max_length=160)),
                ('hero_headline_pt', wagtail.fields.RichTextField(blank=True)),
                ('hero_subhead_pt', wagtail.fields.RichTextField(blank=True)),
                ('cta_label_pt', models.CharField(blank=True, max_length=80)),
                ('services_heading_pt', models.CharField(blank=True, max_length=160)),
                ('services_intro_pt', wagtail.fields.RichTextField(blank=True)),
                ('process_heading_pt', models.CharField(blank=True, max_length=160)),
                ('process_intro_pt', wagtail.fields.RichTextField(blank=True)),
                ('cases_heading_pt', models.CharField(blank=True, max_length=160)),
                ('cases_intro_pt', wagtail.fields.RichTextField(blank=True)),
                ('about_heading_pt', models.CharField(blank=True, max_length=160)),
                ('about_body_pt', wagtail.fields.RichTextField(blank=True)),
                ('closing_heading_pt', models.CharField(blank=True, max_length=200)),
                ('closing_body_pt', wagtail.fields.RichTextField(blank=True)),
                ('stack_note_pt', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StudioThanksPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('heading', models.CharField(blank=True, default='We got it', max_length=160)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('heading_pt', models.CharField(blank=True, max_length=160)),
                ('body_pt', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.CharField(blank=True, max_length=10)),
                ('message', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, help_text='Page slug / campaign that captured this lead.', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.CharField(blank=True, default='', help_text='From CF-IPCountry header.', max_length=2)),
                ('notified', models.BooleanField(default=False, help_text='Notification email sent successfully.')),
                ('notify_error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='studio_book_created_1cb526_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudioCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=160)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('title_pt', models.CharField(blank=True, max_length=160)),
                ('body_pt', wagtail.fields.RichTextField(blank=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='studio.studiohomepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudioProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('title_pt', models.CharField(blank=True, max_length=120)),
                ('description_pt', models.TextField(blank=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='studio.studiohomepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudioServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('output', models.TextField(blank=True, help_text='The typical deliverable / outcome.')),
                ('title_pt', models.CharField(blank=True, max_length=120)),
                ('subtitle_pt', models.CharField(blank=True, max_length=255)),
                ('output_pt', models.TextField(blank=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_cards', to='studio.studiohomepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
