# Generated by Django 5.2.14 on 2026-06-20 20:30

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_studioblogindexpage_studioprojectindexpage'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioSolutionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_eyebrow', models.CharField(blank=True, max_length=160)),
                ('hero_headline', wagtail.fields.RichTextField(blank=True, help_text='Use <em> for emphasis.')),
                ('hero_sub', wagtail.fields.RichTextField(blank=True)),
                ('problem_heading', models.CharField(blank=True, max_length=160)),
                ('problem_body', wagtail.fields.RichTextField(blank=True)),
                ('solution_heading', models.CharField(blank=True, max_length=160)),
                ('solution_body', wagtail.fields.RichTextField(blank=True)),
                ('steps_heading', models.CharField(blank=True, max_length=160)),
                ('benefits_heading', models.CharField(blank=True, max_length=160)),
                ('stats_heading', models.CharField(blank=True, max_length=160)),
                ('proof_note', wagtail.fields.RichTextField(blank=True, help_text="Small 'live in production' trust line.")),
                ('closing_heading', models.CharField(blank=True, max_length=200)),
                ('closing_body', wagtail.fields.RichTextField(blank=True)),
                ('cta_label', models.CharField(blank=True, default='Book a conversation', max_length=80)),
                ('hero_eyebrow_pt', models.CharField(blank=True, max_length=160)),
                ('hero_headline_pt', wagtail.fields.RichTextField(blank=True)),
                ('hero_sub_pt', wagtail.fields.RichTextField(blank=True)),
                ('problem_heading_pt', models.CharField(blank=True, max_length=160)),
                ('problem_body_pt', wagtail.fields.RichTextField(blank=True)),
                ('solution_heading_pt', models.CharField(blank=True, max_length=160)),
                ('solution_body_pt', wagtail.fields.RichTextField(blank=True)),
                ('steps_heading_pt', models.CharField(blank=True, max_length=160)),
                ('benefits_heading_pt', models.CharField(blank=True, max_length=160)),
                ('stats_heading_pt', models.CharField(blank=True, max_length=160)),
                ('proof_note_pt', wagtail.fields.RichTextField(blank=True)),
                ('closing_heading_pt', models.CharField(blank=True, max_length=200)),
                ('closing_body_pt', wagtail.fields.RichTextField(blank=True)),
                ('cta_label_pt', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='studiocase',
            name='link_url',
            field=models.CharField(blank=True, help_text="Optional — when set, the case links to this URL with a 'see more' hint.", max_length=300),
        ),
        migrations.CreateModel(
            name='StudioSolutionBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji.', max_length=8)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(blank=True)),
                ('title_pt', models.CharField(blank=True, max_length=120)),
                ('body_pt', models.TextField(blank=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='studio.studiosolutionpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudioSolutionStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('value', models.CharField(help_text="e.g. '24/7'", max_length=40)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('label_pt', models.CharField(blank=True, max_length=120)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='studio.studiosolutionpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudioSolutionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji.', max_length=8)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(blank=True)),
                ('title_pt', models.CharField(blank=True, max_length=120)),
                ('body_pt', models.TextField(blank=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='studio.studiosolutionpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
