# Generated by Django 5.2.14 on 2026-06-20 20:50

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_studiosolutionpage_studiocase_link_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiosolutionpage',
            name='price_heading',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='studiosolutionpage',
            name='price_heading_pt',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='studiosolutionpage',
            name='price_note',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='studiosolutionpage',
            name='price_note_pt',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='studiosolutionpage',
            name='price_value',
            field=models.CharField(blank=True, help_text="e.g. 'from €1,000'", max_length=80),
        ),
        migrations.AddField(
            model_name='studiosolutionpage',
            name='price_value_pt',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
