# Generated by Django 5.2.14 on 2026-06-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_studiosolutionpage_price_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studioservicecard',
            name='link_url',
            field=models.CharField(blank=True, help_text="Optional — when set, the card links to this URL with a 'see more' hint.", max_length=300),
        ),
    ]
