# Generated by Django 5.2.14 on 2026-05-09 01:20

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0002_blogpostpage_image'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('kind', models.CharField(choices=[('oss', 'Open Source'), ('work', 'Professional'), ('personal', 'Personal / Side')], default='oss', max_length=20)),
                ('period', models.CharField(blank=True, help_text="e.g. '2022-2025'", max_length=100)),
                ('summary', models.CharField(help_text='One-line description shown on cards', max_length=300)),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('tech_stack', models.CharField(blank=True, help_text="Comma-separated, e.g. 'Python, AWS, Postgres'", max_length=300)),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
