# Generated by Django 5.2.14 on 2026-05-09 02:31

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0003_projectindexpage_projectpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='intro_pt',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='body_md_pt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='intro_pt',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='projectindexpage',
            name='intro_pt',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='description_pt',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='summary_pt',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
