# Generated by Django 5.2.14 on 2026-05-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0004_blogindexpage_intro_pt_blogpostpage_body_md_pt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='title_pt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='title_pt',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
