# Generated by Django 5.2.14 on 2026-05-08 00:40

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('bio', wagtail.fields.RichTextField(blank=True)),
                ('skills', wagtail.fields.RichTextField(blank=True, help_text='Stack and skills (markdown-friendly).')),
                ('experience', wagtail.fields.RichTextField(blank=True, help_text='Career highlights, no employer-PII.')),
                ('contact_links', wagtail.fields.RichTextField(blank=True, help_text='LinkedIn / GitHub / email-button.')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Short intro / tagline shown above the fold.')),
                ('body', wagtail.fields.RichTextField(blank=True, help_text='Optional longer content under the intro.')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
