# Generated by Django 5.2.14 on 2026-05-09 02:31

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='bio_pt',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='contact_links_pt',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='experience_pt',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='headline_pt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='skills_pt',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_pt',
            field=wagtail.fields.RichTextField(blank=True, help_text='Portuguese version of body.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_pt',
            field=wagtail.fields.RichTextField(blank=True, help_text='Portuguese version of intro.'),
        ),
    ]
