# Generated by Django 5.2.14 on 2026-05-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoral', '0002_aboutpage_bio_pt_aboutpage_contact_links_pt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='title_pt',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
